linter:
  rules:
    avoid_field_initializers_in_const_classes: false
    avoid_positional_boolean_parameters: false
    directives_ordering: false
    sort_pub_dependencies: false

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    invalid_assignment: error
    missing_return: warning
    dead_code: info
    todo: ignore