name: bling_challenge
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2

  # networking
  http: ^0.13.5

  # logic
  flutter_bloc: ^8.1.2

  # storage
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
